export const AUTH_ERRORS = {
  INCORRECT_EMAIL_OR_PASSWORD_ERR: 'INCORRECT_EMAIL_OR_PASSWORD_ERR',
  UNAUTHORIZED_ERR: 'UNAUTHORIZED_ERR',
  PASSKEY_VERIFICATION_FAILED_ERR: 'PASSKEY_VERIFICATION_FAILED_ERR',
};
