export enum UserActions {
  BOOK_CREATED = 'BOOK_CREATED',
  BOOK_UPDATED = 'BOOK_UPDATED',
  BOOK_REMOVED = 'BOOK_REMOVED',
  BOOK_RATED = 'BOOK_RATED',
  BOOK_ADDED_TO_MUSTREAD = 'BOOK_ADDED_TO_MUSTREAD',
  BOOK_ADDED_TO_WISHLIST = 'BOOK_ADDED_TO_WISHLIST',
  BOOK_ADDED_TO_FAVORITES = 'BOOK_ADDED_TO_FAVORITES',
  BOOK_REMOVED_FROM_MUSTREAD = 'BOOK_REMOVED_FROM_MUSTREAD',
  BOOK_REMOVED_FROM_WISHLIST = 'BOOK_REMOVED_FROM_WISHLIST',
  BOOK_REMOVED_FROM_FAVORITES = 'BOOK_REMOVED_FROM_FAVORITES',
  BOOK_BOUGHT = 'BOOK_BOUGHT',
  COMMENT_ADDED = 'COMMENT_ADDED'
}
