export const USER_VALIDATION_ERRORS = {
  FIRST_NAME_REQUIRED_ERR: 'FIRST_NAME_REQUIRED_ERR',
  LAST_NAME_REQUIRED_ERR: 'LAST_NAME_REQUIRED_ERR',
  EMAIL_REQUIRED_ERR: 'EMAIL_REQUIRED_ERR',
  EMAIL_INVALID_ERR: 'EMAIL_INVALID_ERR',
  PASSWORD_LENGTH_ERR: 'PASSWORD_LENGTH_ERR',
  EMAIL_IN_USE_ERR: 'EMAIL_IN_USE_ERR',
  MISSING_CALLBACK_ERR: 'MISSING_CALLBACK_ERR',
  MISSING_PASSWORD_OR_SALT: 'MISSING_PASSWORD_OR_SALT',
  EMAIL_NOT_FOUND_ERR: 'EMAIL_NOT_FOUND_ERR',
  TOKEN_NOT_FOUND_ERR: 'TOKEN_NOT_FOUND_ERR',
  OLD_PASSWORD_MATCH_ERR: 'OLD_PASSWORD_MATCH_ERR'
};

export const ROLES = {
  ADMIN: 'admin',
  USER: 'user'
};
