export const BOOK_MODEL_NAME = 'Book';

export const BOOK_VALIDATION_ERRORS = {
  TITLE_REQUIRED_ERR: 'TITLE_REQUIRED_ERR',
  AUTHOR_REQUIRED_ERR: 'AUTHOR_REQUIRED_ERR',
  BOOK_NOT_FOUND_ERR: 'BOOK_NOT_FOUND_ERR'
};
