name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Format check
        run: npx nx format:check

      - name: Lint
        run: npx nx affected --target=lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Run tests
        run: npx nx affected --target=test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Build
        run: npx nx affected --target=build

  publish:
    name: Build & Push Docker Image
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Check if api is affected
        id: check-api-affected
        run: |
          if npx nx show projects --affected --type=app | grep -q "^api$"; then
            echo "api is affected - proceeding with Docker build"
            echo "affected=true" >> $GITHUB_OUTPUT
          else
            echo "api is not affected - skipping Docker build"
            echo "affected=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check-api-affected.outputs.affected == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.check-api-affected.outputs.affected == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check-api-affected.outputs.affected == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/bookapp-api:latest

      - name: Skip Docker build
        if: steps.check-api-affected.outputs.affected == 'false'
        run: echo "Docker build skipped - api project not affected by changes"
